### ISSUE TITLE
Things to add/modify

### ISSUE THREAD

**Issue by mkfink** [i3detroit/i3-map-board#2]
Small bathroom shower light
Small bathroom shower fan
Tool crib workbench lights (add second LED)
Elab arch lights (add second LED)

**Comment by abzman** [comment]
these should all be online now

**Comment by mkfink** [comment]
Update
~Small bathroom shower light~
~Small bathroom shower fan~
Tool crib workbench lights (add second LED)
Elab arch lights (add second LED)

**Comment by mkfink** [comment]
All added
